Start using AssetRegistry
piever/InteractBulma.jl pull request #11
Opened 2018-06-18 09:14 UTC by ranjanan

Hi, 

I wanted to send this PR to use `AssetRegistry.jl`. This allows users to serve assets from arbitrary file and folder locations. 

The css file locations are specified as `consts` because this would facilitate static compilation and shipping.

2018-06-19 09:32 UTC, piever requested changes

2018-06-19 09:32 UTC, piever commented on src/InteractBulma.jl
> +        [AssetRegistry.register(main_css)] :
Similar question as in InteractBase: would simply using `[main_css]` and dropping the direct dependency on AssetRegistry also work? Sorry for being a bit of a pain on this one but am still trying to understand what's the correct usage of AssetRegistry

2018-06-19 11:11 UTC, piever commented on src/InteractBulma.jl
> +        [AssetRegistry.register(main_css)] :
IIUC, here we should wait for the new WebIO release that fixes passing the path to `import!` and then remove the AssetRegistry dependency

2018-06-20 03:02 UTC, shashi commented on src/InteractBulma.jl
> +        [AssetRegistry.register(main_css)] :
It's done.

2018-06-20 07:00 UTC, shashi commented on src/InteractBulma.jl
> +        [AssetRegistry.register(main_css)] :
Why do we have a condition that checks for IJulia here?

2018-06-20 07:26 UTC, ranjanan commented on src/InteractBulma.jl
> +        [AssetRegistry.register(main_css)] :
@piever my bad once again, you don't need `register` there. Updating the PR.

2018-06-20 10:48 UTC, piever commented on src/InteractBulma.jl
> +        [AssetRegistry.register(main_css)] :
@ranjanan thanks for updating should be good now

@shashi I use a different library for IJulia: Bulma css is "invasive" and would screw up the notebook layout, so I recompiled a version that only works for elements with the class `interactbulma` and I call that one in IJulia rather than the normal ones

2018-06-20 11:17 UTC, shashi commented on src/InteractBulma.jl
> +        [AssetRegistry.register(main_css)] :
OK. That's great!

BTW WebIO has an `iframe` function which wraps anything in an iframe but still keeps the communication working with the parent window.

However it may not be an ideal solution in this case as can end up with tens of iframes -- one for each widget.

2018-06-20 11:20 UTC, piever commented on src/InteractBulma.jl
> +        [AssetRegistry.register(main_css)] :
Maybe one could define a way in WebIO to only put the "outer node" in a `iframe`, not sure how simple/clean that is though

2018-06-22 11:44 UTC, piever approved these changes

2018-06-22 11:44 UTC, merged